import Head from 'next/head'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import Ourwork from '../components/Ourwork'
import Testimonials from '../components/Testimonials'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Enterprise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar/>
      <Hero/>
      <Testimonials/>
      <Ourwork/>
      
    </div>
  )
}
